### ISSUE TITLE
Stream Final Agent Response

### ISSUE THREAD

**Issue by 0ptim** [0ptim/JellyChat#45]
### Description

We want to stream the tokens from the final output of the agent. 

This allows the user to start reading the response as soon as it starts to get generated, instead of waiting until the whole answer is done.

This should greatly improve the time until a response is visible to the user, especially for longer answers. It would also make the bot feel more “alive”, since it would feel more like someone who's typing in real-time.

### Implementation

- When I use [`on_llm_new_token`](https://github.com/hwchase17/langchain/blob/931e68692e75ae22ab245c4d8d24b62c1f95cc59/langchain/callbacks/base.py#L297C1-L298C1) this does not work, because all sort of output is then streamed.
- [`FinalStreamingStdOutCallbackHandler` ](https://python.langchain.com/docs/modules/agents/how_to/streaming_stdout_final_only)does not work because it was written for the `ZERO_SHOT_REACT_DESCRIPTION` agent.

### Todo's

- [x] Wait for possible answer on LangChain discord support forum
- [x] Wait for implementation of harisrab
  - Implementation works, but the final answer is only streamed **after** the final answer was generated fully by the LLM. This looks nice, but does not improve the time on how long the user has to wait for an answer.
- [x] Waiting again for response of harisrab
- [x] Implement backend
- [x] Implement frontend
- [x] Final testing
- [ ] Documentation of new stream over web socket in [README](https://github.com/0ptim/JellyChat/blob/main/backend/README.md#web-socket)

### Resources

- [Base class](https://github.com/hwchase17/langchain/blob/931e68692e75ae22ab245c4d8d24b62c1f95cc59/langchain/callbacks/base.py#L225) callback handler
- [Gist](https://gist.github.com/harisrab/8fc67827ebf3acb997398b5252869351) shared by harisrab for implementation with React Agent
